version: '3.8'

networks:
  data_migrations:
    name: data_migrations
    driver: bridge

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mysql_database
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
    volumes:
      - ./mysql_init:/docker-entrypoint-initdb.d
    networks:
      - data_migrations
    ports:
      - 3306:3306

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: postgres_user
      POSTGRES_DB: postgres_database
    volumes:
      - ./postgres_init:/docker-entrypoint-initdb.d
    networks:
      - data_migrations
    ports:
      - 5432:5432

  nifi:
    image: apache/nifi:latest
    container_name: nifi
    #restart: always
    # environment:
    #   - NIFI_WEB_HTTP_HOST='0.0.0.0'
    #   - NIFI_WEB_HTTP_PORT=8080
    #   - NIFI_WEB_HTTPS_PORT=8443
    #   - SINGLE_USER_CREDENTIALS_USERNAME=admin
    #   - SINGLE_USER_CREDENTIALS_PASSWORD=admin
    ports:
      # HTTP
      - 8080:8080/tcp
      # HTTPS
      - 8443:8443/tcp
      # Remote Input Socket
      - 10000:10000/tcp
      # JVM Debugger
      - 8000:8000/tcp
      # Cluster Node Protocol
      #- 11443:11443/tcp
    volumes:
      - ./nifi/database_repository:/opt/nifi/nifi-current/database_repository
      - ./nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./nifi/content_repository:/opt/nifi/nifi-current/content_repository
      - ./nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ./nifi/state:/opt/nifi/nifi-current/state
      - ./nifi/logs:/opt/nifi/nifi-current/logs
      # conf directory cannot be mounted as a volume
      # it contains already existing configuration files
      # without them nifi will not start
      # - ./nifi/conf:/opt/nifi/nifi-current/conf
    networks:
      - data_migrations
